In [1]:
import numpy as np

In [2]:
numpy_arr = np.array([1, 2, 3, 4])
print('Here is a NumPy array:', numpy_arr)
print('You know it is a NumPy array because its type is:', type(numpy_arr))

Here is a NumPy array: [1 2 3 4]
You know it is a NumPy array because its type is: <class 'numpy.ndarray'>


In [3]:
list_of_integers = [0, 1, 2, 3]

In [5]:
list_of_integers + [3]

[0, 1, 2, 3, 3]

In [6]:
array_of_integers = np.array(list_of_integers)
array_of_integers + 3

array([3, 4, 5, 6])

In [7]:
lengths_of_each_room = np.array([10, 12, 20, 5])
widths_of_each_room = np.array([13, 15, 16, 4])
areas_of_each_room = lengths_of_each_room * widths_of_each_room
print ('Here is an array with the square footages for each room:', areas_of_each_room)

Here is an array with the square footages for each room: [130 180 320  20]


In [8]:
nyc_avg_temps_f = [39, 42, 50, 62, 72, 80, 85, 84, 76, 65, 54, 44]


In [9]:
np_nyc_avg_temps_f = np.array(nyc_avg_temps_f)
np_nyc_avg_temps_c = (np_nyc_avg_temps_f - 32) * (5/9)

In [10]:
np_nyc_avg_temps_c

array([ 3.88888889,  5.55555556, 10.        , 16.66666667, 22.22222222,
       26.66666667, 29.44444444, 28.88888889, 24.44444444, 18.33333333,
       12.22222222,  6.66666667])

In [11]:
x = np.array([1, 2, 3])
print(type(x))

<class 'numpy.ndarray'>


In [12]:
x*3

array([3, 6, 9])

In [13]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [14]:
y.shape

NameError: name 'y' is not defined

In [15]:
y = np.array([[1, 2], [3, 4]])


In [16]:
y.shape

(2, 2)

In [23]:
py_list = [0,1,2,3,4]
py_range = range(0, 5)
array_from_list = np.array(py_list)
array_from_range = np.array(py_range)

In [26]:
list_height_inches = [65, 68, 73, 75, 78]
array_heights_inches = np.array(list_height_inches)
array_heights_meters = array_heights_inches * 0.0254

array([1.651 , 1.7272, 1.8542, 1.905 , 1.9812])

In [32]:
list_weight_pounds = [150, 140, 220, 205, 265]
array_weights_pounds = np.array(list_weight_pounds)
array_weights_kg = array_weights_pounds / 2.2046

array_bmi = array_weights_kg / (array_heights_meters * array_heights_meters)
array_bmi

array([24.9613063 , 21.28692715, 29.02550097, 25.62324316, 30.62382485])

In [36]:
identity = np.ones(len(array_bmi))


array([1., 1., 1., 1., 1.])

In [37]:
array_bmi * identity

array([24.9613063 , 21.28692715, 29.02550097, 25.62324316, 30.62382485])

In [42]:
f = open('bp.txt')
n_rows = len(f.readlines())
print('The file has {} lines.'.format(n_rows)) 
f = open('bp.txt') 
n_cols = (len(f.readline().split('\t'))) 

f = open('bp.txt')

# Your code here
# Pseudocode outline below
#1) Create a matrix of zeros that is the same size of the file
matrix = np.zeros([n_rows, n_cols])
#2) Iterate through the file: "for line in f:" Hint: using enumerate will also be required
for n, line in enumerate(f):
    if n > 0:
        matrix[n,:] = line.split('\t')
    #3) Update each row of the matrix with the new stream of data
    #Hint: skip the first row (it's just column names, not the data.)


FileNotFoundError: [Errno 2] No such file or directory: 'bp.txt'